POST http://localhost:8000/api/user/subCoins HTTP/1.1
content-type: application/json

{
    "userId": "5fd9653f258cd52204434ec5",
    "coins": 50
}
###
GET http://localhost:8000/api/users 
###
POST http://localhost:8000/api/maps/users HTTP/1.1
content-type: application/json
 
 
{
    "userId": "5fd9653f258cd52204434ec5",
    "mapId": "5fd965568411ba5b6818f5b4"
}

###
GET http://localhost:8000/api/maps
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmYxMjZkODk2YTBmNTM4MTRhYzJmMDMiLCJlbWFpbCI6Im5mZXkxQG1lLmNvbSIsInVzZXJuYW1lIjoibmZleSIsImlhdCI6MTYxMDQyNDQzNiwiZXhwIjoxNjEwNDMxNjM2fQ.3zJGOV0PGS64uj2dF-hyjKGDGXoWM0p_Tpd8ZMuMlaU

###

POST http://localhost:8000/api/queues
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmYxMjZkODk2YTBmNTM4MTRhYzJmMDMiLCJlbWFpbCI6Im5mZXkxQG1lLmNvbSIsInVzZXJuYW1lIjoibmZleSIsImlhdCI6MTYxMDQxNjgyNSwiZXhwIjoxNjEwNDI0MDI1fQ.rzPvN349yVX2yE_NnLxRsBW8XD7FJ6MOmMl_rIeJShM

{
    "mapHeightLength": "5",
    "tickTotal": "10",
    "tickTime": "60",
    "playerCapacity": "2"
}

###

GET http://localhost:8000/api/queues
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmYxMjZkODk2YTBmNTM4MTRhYzJmMDMiLCJlbWFpbCI6Im5mZXkxQG1lLmNvbSIsInVzZXJuYW1lIjoibmZleSIsImlhdCI6MTYxMDQxNjgyNSwiZXhwIjoxNjEwNDI0MDI1fQ.rzPvN349yVX2yE_NnLxRsBW8XD7FJ6MOmMl_rIeJShM
###
POST http://localhost:4000/login
content-type: application/json

{
    "email": "asdf@zxcv.com",
    "password": "asdfzxcv"
}

###
POST http://localhost:4000/register
content-type: application/json

{
    "firstName": "N",
    "lastName": "F",
    "email": "nfey1@me.com",
    "password": "N132435fCf!",
    "username": "nfey"
}
###
GET http://localhost:8000/api/queues/5fedb5423bbdc913c03717bc/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFkOWU5ZjE0ZWNkYTUwNDZmOWE1ZjYiLCJlbWFpbCI6Im5mZXkxQG1lLmNvbSIsInVzZXJuYW1lIjoid2F0dHl3YWh3YWgiLCJpYXQiOjE2MDk0MTM4MjUsImV4cCI6MTYwOTQyMTAyNX0.ElBeVl3AC7jRpNoA5QeK9yDAYJ6EQt2VGBIsQ_rYvFY
###
GET http://localhost:8000/api/pixels/5ffd0472db446c2b444d9ad6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmYxMjZkODk2YTBmNTM4MTRhYzJmMDMiLCJlbWFpbCI6Im5mZXkxQG1lLmNvbSIsInVzZXJuYW1lIjoibmZleSIsImlhdCI6MTYxMDQxNjgyNSwiZXhwIjoxNjEwNDI0MDI1fQ.rzPvN349yVX2yE_NnLxRsBW8XD7FJ6MOmMl_rIeJShM
###
POST http://localhost:8000/api/pixels/takeInitialTurnAsync
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQ5NjUzZjI1OGNkNTIyMDQ0MzRlYzUiLCJlbWFpbCI6ImFzZGZAenhjdi5jb20iLCJ1c2VybmFtZSI6ImFzZGYiLCJpYXQiOjE2MTA0MjU1MDcsImV4cCI6MTYxMDQzMjcwN30.MuAMk6v0vfwkbFEcKPPJEZKonFKW9Jkk-CJRBS1Z8ks
content-type: application/json

{
    "pixel": {
        "map_pos": {
            "map": "5ffd0472db446c2b444d9acc",
            "x": "1",
            "y": "1"
        },
        "color": "brown",
        "heat": "0",
        "effect": "none",
        "strength": "1",
        "attackers": [],
        "_id": "5ffd0472db446c2b444d9acd",
        "createdAt": "2021-01-12T02:07:46.188Z",
        "updatedAt": "2021-01-12T02:07:46.188Z",
        "__v": "0"
    },
    "map": "5ffd0472db446c2b444d9acc"
}
###
GET http://localhost:8000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQ5NjUzZjI1OGNkNTIyMDQ0MzRlYzUiLCJlbWFpbCI6ImFzZGZAenhjdi5jb20iLCJ1c2VybmFtZSI6ImFzZGYiLCJpYXQiOjE2MTA0MjEzMjEsImV4cCI6MTYxMDQyODUyMX0.tYk3kIwCiG23UcneOFr3JfTq6h7HE3eUIsCoGBTLFUA
###

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQ5NjUzZjI1OGNkNTIyMDQ0MzRlYzUiLCJlbWFpbCI6ImFzZGZAenhjdi5jb20iLCJ1c2VybmFtZSI6ImFzZGYiLCJpYXQiOjE2MTA0MjQ0MDUsImV4cCI6MTYxMDQzMTYwNX0.RxVN5zXzuki-A7DT5suekA_brAKUVRgnyLLqB3aED2w
^asdf

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQ5NjUzZjI1OGNkNTIyMDQ0MzRlYzUiLCJlbWFpbCI6ImFzZGZAenhjdi5jb20iLCJ1c2VybmFtZSI6ImFzZGYiLCJpYXQiOjE2MTA0MjU1MDcsImV4cCI6MTYxMDQzMjcwN30.MuAMk6v0vfwkbFEcKPPJEZKonFKW9Jkk-CJRBS1Z8ks
^nfey
